# Generated by Django 6.0 on 2025-12-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createde_data',
            new_name='created_data',
        ),
    ]
